### ISSUE TITLE
[BUG] New Discord Stable Build

### ISSUE THREAD

**Issue by C0D6WasTaken** [finnjosten/Zelk-Discord-Theme-Fixes#21]
Recently, Discord has updated to a new stable version, thus breaking some components of the theme.
### What is still working?
Button colours seem to still be working. Yes, that's more or less everything.

**Comment by ripdog** [comment]
Same here. Example issues: 
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/174944/d8f3b531-04ad-41e3-989c-063c9bbceadc)
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/174944/93e19fe0-453b-4968-afad-d5bc05a0c8ca)
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/174944/61416e59-a100-4e67-96a5-9c2d14bc111c)

**Comment by finnjosten** [comment]
Thanks for making an issue!

I will be looking into this, unfortunately discord keeps removing my better discord so I don't see bugs to often

**Comment by finnjosten** [comment]
Seems either my better discord is broken or the whole of Zelk no longer works.

edit:
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/117974776/db08bd87-3044-4689-9909-d23a5d0ec087)
Well this explains it. ATM i will have to wait for better discord to be update itself then look into fixing Zelk but i am not sure if that is going to be possible. I will keep you all updated!

edit 2:
I have been able to get zelk to partially work again but BD keeps crashing when i try to open my dev menu :)

**Comment by ripdog** [comment]
Have you tried Vencord? It mostly seems to still work.

**Comment by ripdog** [comment]
From the Vencord server:
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/174944/07f4e9d3-b84b-40a9-860a-3f092a0e2b68)

**Comment by finnjosten** [comment]
Sticking with BD just have to wait until it fixes the dev menu

**Comment by finnjosten** [comment]
I have pushed an update. Let me know if it works. (it seems to be working for me)

**Comment by C0D6WasTaken** [comment]
It seems to be working.
There are some small things to fix like the settings screen not expanding (using all the empty space), but otherwise nicely done 👍

**Comment by finnjosten** [comment]
Yeah I just made a temp fix so it's atleast usable. I will fix the rest when my discord starts behaving again

**Comment by finnjosten** [comment]
> It seems to be working.
> There are some small things to fix like the settings screen not expanding (using all the empty space), but otherwise nicely done 👍  

Also this is default zelk behaviour and I won't change it

**Comment by Ultra980** [comment]
It still doesn't work for me.
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/90788596/bd8cc809-83d9-4e2d-a13a-3df8e7f83deb)

**Comment by finnjosten** [comment]
Are you sure you added the @import()? Because i seem to be having no issue at all

**Comment by Ultra980** [comment]
[yes](https://github.com/Ultra980/zelk/blob/main/zelkBD.theme.css#L17)

**Comment by finnjosten** [comment]
Can you check via the developer menu to see if the styling is applied of maybe over writen? Also make sure to check that the import is inside the files on your pc (BD has a theme file editor idk about vencord) as for god knows what reason it can happen that it doesnt update

**Comment by Ultra980** [comment]
I manually added the content of the CSS in the quickcss editor, and it seems to sorta work...

![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/90788596/83b451e7-bea6-49e7-a338-2ed2b96dfdaa)

**Comment by finnjosten** [comment]
Yeah due to discords update everything was broken and i only fixed the most important parts as i havent been able to use the dev menu (discords app is broken). Also the reason why its broken on that page is because this theme is meant to be used in betterdiscord (and goosemod). even though vencord supports it, stuff can break as they use different classes for their own buttons and all.

**Comment by Ultra980** [comment]
But it's broken in every settings page
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/90788596/bbf63c99-3ebe-4b54-8410-713a5980510f)

**Comment by Ultra980** [comment]
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/90788596/646c07ba-61f4-44d4-818d-05c8b1c4917e)
it's also broken here

**Comment by finnjosten** [comment]
![image](https://github.com/BlackSparowYT/Zelk-Discord-Theme-Fixes/assets/117974776/2dc5b686-c7ce-4d39-b0ec-460534cb50cd)
i will change the color there so its more in line with all the other buttons

**Comment by finnjosten** [comment]
I updated it let me know if in the settings area its still bugged

**Comment by Ultra980** [comment]
It's fixed in the settings area, but not in the new messages area.

**Comment by finnjosten** [comment]
Have you noticed that basicly the whole theme is broken or not? I now there are issues but at the moment i cant help it. The dev menu in discord is screwed and causes crashes and i cant fix anything. You will have to live with the issues for some time till discord fixes their app.

And if you want to help me. Make a trello board with all the bugs you find then invite me to it. Make sure to add images or be clear about the issue in descriptions.

**Comment by finnjosten** [comment]
Looks like discord has fixed the issue with f12 causing it to crash so i will be slowly updating this again
